<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="decode_tolerance_tests.TestDecodeToleranceTests-20181018122124" skipped="0" tests="1" time="0.001" timestamp="2018-10-18T12:21:24">
	<testcase classname="decode_tolerance_tests.TestDecodeToleranceTests" name="testDecodeToleranceWhenFourBandResistorAndFourthBandIsBrown" time="0.001" timestamp="2018-10-18T12:21:24">
		<error message="name 'assertEquals' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/Users/ras/Projects/Python/cs3280/project2/src/unittest/python/decode_tolerance_tests.py", line 9, in testDecodeToleranceWhenFourBandResistorAndFourthBandIsBrown
    assertEquals(result, 1.0)
NameError: name 'assertEquals' is not defined
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
